POST  http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxMjMiLCJpZCI6IjYyZjUwNGI1MDdjNThiZDQ5MTY2Yjg4MiIsImlhdCI6MTY2MDIyNDczOH0.1BJ_o8Li0oLr9-32ZkWMhpgbh5RBr0v7VlDp5lklTZI

{
      "title": "Test if tokens work",
      "author": "I guess they work",
      "url": "yay.com",
      "likes": 5,
      "userId": "62f504b507c58bd49166b882"
}