DELETE     http://localhost:3003/api/blogs/62f551153354703459aede3a HTTP/1.1
content-type: application/json

{
      "username": "roosdadat123",
      "name": "root",
       "password": "toor"
}

   //   "title": "How to kill your ex",
   //   "author": "John T Roosevelt",
   //   "url": "voggov.com",
   //   "likes": "5000"

   //   "username": "root123",
   //   "name": "root",
   //    "password": "toor"